import { DEFAULT_PORTS } from "../../shared/PORTS.js"

export const ACCESS_TYPE = Object.freeze({
    LOCAL: "LOCAL", // LOCAL IS FOR ADMIN DASHBOARD
    PUBLIC: "PUBLIC", // PUBLIC IS FOR MEMBER DASHBOARD
})

export const PORTS = Object.freeze({
    LOCAL: DEFAULT_PORTS.LOCAL_PORT,
    PUBLIC: DEFAULT_PORTS.PUBLIC_PORT,
})

export const DEV_ACCESS_TYPE = ACCESS_TYPE.PUBLIC // CHANGE THIS TO TEST DIFFERENT ACCESS TYPES

export const DEV_PORT = PORTS[DEV_ACCESS_TYPE]
